### ISSUE TITLE
Event vor Abschluss der Initialisierung

### ISSUE THREAD

**Issue by kveldscholten** [DirkPersky/typo3-dp_cookieconsent#61]
Ich würde gerne vorm öffnen der Cookiebox ein leicht durchsichtigen Hintergrund hinzufügen wollen.
`$('<div id="dp--cookie-consent-bg"/>').prependTo('body');`

Wenn ich den Code im dp--cookie-init Event packe wird das Element erst hinzufügt während sich die Cookiebox schon öffnet was recht unschön aussieht.
```
document.addEventListener('dp--cookie-init', function (e) {
    $('<div id="dp--cookie-consent-bg"/>').prependTo('body');
});
```

Die anderen Events treffen soweit verständlich ebenso nicht zu.
Gibt es da eine andere Möglichkeit?

**Comment by DirkPersky** [comment]
Wie wäre es mit einer CSS lösung?

```css
.cc-window:before {
    display: block;
    content: '';
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: #000;
    z-index: -1;
    opacity: .6;
}
```
