### ISSUE TITLE
Block site usage until interaction with cookieconsent

### ISSUE THREAD

**Issue by marius-social** [DirkPersky/typo3-dp_cookieconsent#76]
Hi there,

is it possible to block site usage until the user interacts with cookieconsent? So you'll actively have to decide for or against cookies rather than ignoring the consent box while using the site. Like an overlay over the site, making a decision mandatory.

I couldn't find anything like that in the documentation.

Thanks for help!

**Comment by DirkPersky** [comment]
he, 

u can try this CSS for it

```css
body.dp--cookie-consent {
    overflow: hidden;
    max-height: 100vh;
}
body.dp--cookie-consent .cc-window:before {
    content: '';
    display: block;
    background-color: rgba(0,0,0,.8);
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
}
```
